---
title: "BA-seminar Ulighed i uddannelse"
author: "Simon Calmar Andersen"
date: "11/11/2020"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: true
    number_sections: true
    theme: united
    code_folding: "hide"

link-citations: true
      


knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introduktion: Ulighed i uddannelse

Et af de måske mest stabile, universelle fænomener i samfundsvidenskaberne er, at børn af lavtuddannede forældre, selv har en højere risiko for at få ingen eller kort uddannelse. Samtidig lever lavtuddannede og deres børn i større grad i fattigdom, med svær overvægt, med stress og depression, og de dør tidligere. Det er et mål for mange velfærdsstater at bryde med denne ulighed ved at give alle børn samme forudsætninger i udgangspunktet----\textit{levelling the playing field}. Alligevel reproduceres denne ulighed i uddannelse generation efter generation.

I dette fag skal vi læse den nyeste forskning i, hvad der kan være årsager til denne ulighed, samt hvad effekten er af forskellige uddannelsespolitikker, som forsøger at udjævne ulighed i uddannelse. Vi skal sammen diskutere og prøve at forstå, hvordan uddannelsespolitikken kan indrettes, så det begrænser ulighed i uddannelse. Det er en problemstilling, som kræver, at vi trækker på teori og forskning fra både psykologi, uddannelsesøkonomi og offentlig forvaltning -- herunder teorier om implementering og samproduktion.

Et sigte med seminaret er, at deltagerne selv bidrager med ny empirisk viden enten ved at analysere eksisterende datakilder på nye måder eller ved at indsamle nye data selv. Derfor er det et selvstændigt formål med seminaret at klæde deltagerne på til at kunne gennemføre og afrapportere kvantitative analyser. Metodiske overvejelser og diskussion af, hvordan konkrete problemstillinger kan undersøges i en opgave, vil således stå centralt i hele seminaret. Vi skal sideløbende arbejde med at anvende metoder såsom eksperimenter, regression discontinuity og fixed effects designs. En stor del af seminaret vil fokusere på, hvad der kendetegner en god opgave, og hvordan deltagerne kan omsætte ideer til gode problemstillinger og analysedesign. Endelig vil en del af seminaret fungere som en ramme for den enkeltes opgaveskrivning med vejledning og feedback fra de øvrige deltagere.

## Rammer for faget

**Fra studieordningen**

-   Målet er, at de studerende efter at have deltaget i forelæsninger og holdundervisning kan:

        + redegøre for udvalgte teorier, metoder og sagsforhold inden for faget
        + sammenligne fagets teorier, metoder og sagsforhold og kan identificere disses forskelle/ligheder og styrker/svagheder.
        + selvstændigt formulere en problemstilling, der er relateret til fagets teorier, metoder og sagsforhold.
        + anvende teorier, approaches, metoder, og data, der er relevante for belysningen af den valgte problemstilling.
        + vurdere frugtbarheden af fagets teorier, metoder og deres anvendelsesområder.

-   Bachelorprojektseminaret afsluttes med en hjemmeopgave, hvori der behandles en nærmere afgrænset problemstilling inden for seminarets genstandsfelt.

-   I tilknytning til udarbejdelsen af hjemmeopgaven gives der målrettet indføring i udformning af opgave- og forskningsdesign ligesom der ydes opgavevejledning.

-   Der undervises i et omfang svarende til 4 timer om ugen i 11 uger. Hertil kommer individuel vejledning.

-   Pensum aftales med underviser og fastlægges i forhold til afhandlingens problemstilling. Det antages dog at have et omfang på 1.200 - 1.700 sider.

-   Opgavebesvarelsen må have et omfang på maksimalt 70.000 anslag (inkl. mellemrum), inkl. bilag og noter, men ekskl. indholdsfortegnelse, litteraturliste og engelsk resumé. Resuméet indgår i bedømmelsen. Besvarelser, der overskrider det normerede omfang, vil blive afvist.

## Undervisningsplan

+-----+----+-------------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Uge | \# | Emne                                      | Metode                               | Pensum                                                                                                                                                                              |
+=====+====+===========================================+======================================+=====================================================================================================================================================================================+
| 5   | 1  | [Introduktion: Ulighed i uddannelse]      | Intro: Opgaveskrivning               | @udesen2020, pp. 1-15; @landerso_scandinavian_2017; @mayer_what_1997, pp. 1-15                                                                                                      |
+-----+----+-------------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 6   | 2  | [Arv og miljø]                            | Problemstilling                      | @cunha2007; @kong2018; @engzell_heritability_2019; @morris_too_2020; @engzell_reply_2020; @king_designing_1994, kap. 1 (tilgængelig [her](https://www.jstor.org/stable/j.ctt7sfxj)) |
+-----+----+-------------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 7   |    | Finde problemstilling                     |                                      |                                                                                                                                                                                     |
+-----+----+-------------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 8   | 3  | [Elever og selvkontrol]                   | Litteratursøgning og referencesystem | @inzlicht2021; @cotton2020a; @damgaard_nudging_2018                                                                                                                                 |
+-----+----+-------------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9   | 4  | [Klassekammerater og peer effects]        | RCT                                  | @sacerdote_experimental_2014; @yeager_national_2019; @junge_administrative_2020; @angrist_mastering_2014 Intro, kap. 1                                                              |
+-----+----+-------------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10  | 5  | [Forældre og coproduction]                | Regression og Instrumentvariable     | @parks1981; @andersen2016; @angrist_mastering_2014 kap. 2 og 3                                                                                                                      |
+-----+----+-------------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 11  | 6  | [Lærere og coping]                        | Regression Discontinuity             | @lipsky_street-level_1980, kap. 7; @andersen_reducing_2019; @angrist_mastering_2014 kap. 4                                                                                          |
+-----+----+-------------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 12  | 7  | [Skoleledere og beslutningstagning]       | Databehandling                       | @meier_proverbs_2009; @andersen2020                                                                                                                                                 |
+-----+----+-------------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 13  |    | Dataanalyse                               |                                      |                                                                                                                                                                                     |
+-----+----+-------------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 14  | 8  | [Politikere og strukturelle rammer]       | Difference-in-differences            | @hanushek_failure_2003; @andersen_increasing_2016; @angrist_mastering_2014 kap. 5                                                                                                   |
+-----+----+-------------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 15  | 9  | [Opskalering og implementering]           | Målingsvaliditet                     | @banerjee_proof_2017; @lortie-forgues_rigorous_2019                                                                                                                                 |
+-----+----+-------------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 16  | 10 | [Skolesystemer og performance management] |                                      |                                                                                                                                                                                     |
+-----+----+-------------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 17  | 11 | [Synopsisgennemgang]                      |                                      |                                                                                                                                                                                     |
+-----+----+-------------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 18  |    | Individuel vejledning                     |                                      |                                                                                                                                                                                     |
+-----+----+-------------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 19  |    |                                           |                                      |                                                                                                                                                                                     |
+-----+----+-------------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 20  | 12 | [Opgavegennemgang]                        |                                      |                                                                                                                                                                                     |
+-----+----+-------------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 21  |    | Individuel vejledning                     |                                      |                                                                                                                                                                                     |
+-----+----+-------------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 22  |    |                                           |                                      |                                                                                                                                                                                     |
+-----+----+-------------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 23  |    |                                           |                                      |                                                                                                                                                                                     |
+-----+----+-------------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 24  |    | Eksamen                                   |                                      | Tidspunkt ligger ikke fast                                                                                                                                                          |
+-----+----+-------------------------------------------+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Undervisningsplan

# Arv og miljø

> **Spørgsmål til arv og miljø**
>
> 1.  Hvor meget kan gener forklare af ulighed i uddannelse?
>
> 2.  Hvordan betyder gener noget for børns uddannelseschancer?
>
> 3.  Hvad betyder forældres adfærd over for børn
>
> 4.  Hvordan betyder gener og mijøet i hjemmet noget forskelligt for forskellige børn?
>
> 5.  Hvilken betydning har den nyeste viden om arv og miljø for, hvordan uddannelsespolitikken må indrettes?

> **Spørgsmål til Metode**
>
> 6.  Hvad er en god problemstilling for en opgave?

# Elever og selvkontrol

> **Spørgsmål til Elever og selvkontrol**
>
> 1.  Hvad er en god problemstilling for en opgave?

# Klassekammerater og peer effects

# Forældre og coproduction

# Lærere og coping

# Skoleledere og beslutningstagning

# Politikere og strukturelle rammer

# Opskalering og implementering

# Skolesystemer og performance management

# Synopsisgennemgang

# Opgavegennemgang

# Eksamen

# Pensum
